"""Added org_description

Revision ID: 40f1268a4993
Revises: f31a8e261b67
Create Date: 2025-05-04 14:40:28.438468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f1268a4993'
down_revision = 'f31a8e261b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_description', sa.String(length=800), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('org_description')

    # ### end Alembic commands ###
