"""initial migration

Revision ID: 78c5679e09cd
Revises: 
Create Date: 2025-04-19 13:17:46.681578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c5679e09cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('phoneNumber', sa.String(length=225), nullable=True),
    sa.Column('websiteLink', sa.String(length=225), nullable=True),
    sa.Column('fileName', sa.String(length=225), nullable=True),
    sa.Column('mediaData', sa.LargeBinary(), nullable=True),
    sa.Column('mediaType', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('websiteLink')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    # ### end Alembic commands ###
