"""Added user model

Revision ID: b50a87b30380
Revises: 83327fb917de
Create Date: 2025-06-05 18:03:15.522850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50a87b30380'
down_revision = '83327fb917de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('phone_number', sa.String(length=225), nullable=True),
    sa.Column('preferred_currency', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
