"""Updated var casing (converted to proper Python casing)

Revision ID: c69f7b267900
Revises: 78c5679e09cd
Create Date: 2025-04-27 19:04:30.706174

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c69f7b267900'
down_revision = '78c5679e09cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('website_link', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('media_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint('organization_websiteLink_key', type_='unique')
        batch_op.create_unique_constraint(None, ['website_link'])
        batch_op.drop_column('mediaType')
        batch_op.drop_column('websiteLink')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('fileName')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('mediaData')
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mediaData', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fileName', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('websiteLink', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mediaType', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('organization_websiteLink_key', ['websiteLink'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_data')
        batch_op.drop_column('file_name')
        batch_op.drop_column('website_link')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
